cats = [["Замороженные полуфабрикаты", "Frozen semi -finished products"],
        ["Чай и  не кофе ", "Tea and not coffee"],
        ["Напитки", "Beverages"],
        ["Молочные и не молочные продукты", "Dairy and non -dairy products"],
        ["Суперфуды", "Superfoods"],
        ["Все для выпечки", "All for baking"],
        ["Масла", "Oils"],
        ["Специи, соли и соусы", "Spices, salt and sauces"],
        ["НЕсахар", "Notsugar"],
        ["Пасты", "Pastes"],
        ["Сладенькое", "Sweet"],
        ["Давай завтракать", "Let's have breakfast"],
        ["Снэки", "Snacks"],
        ["Хлебцы", "Bread"],
        ["Орешки и сухофрукты", "Nuts and dried fruits"],
        ["Макароны и крупы", "Pasta and cereals"],
        ["Соевые веган продукты", "Soy vegan products"],
        ["Яйца", "Eggs"]
]

subcats = [[1, "Замороженные полуфабрикаты", "Frozen semi -finished products"],
           [1, "Мороженое", "Ice cream"],
           [2, "Чай", "Tea"],
           [2, "Некофе и напитки", "Not coffee and drinks"],
           [2, "Какао и кероб", "Cocoa and kerobr"],
           [3, "Соки", "Juices"],
           [3, "Комбуча и энергетики", "Combuchery and energy"],
           [3, "Вода", "Water"],
           [4, "Айран, сливки", "Ayran, cream"],
           [4, "Козье молоко", "Goat milk"],
           [4, "Растительное молоко", "Vegetable milk"],
           [4, "Сыры и тофу", "Cheeses and tofu"],
           [5, "Семена", "Seeds"],
           [5, "Клетчатки и отруби", "Fiber and bran"],
           [5, "Суперфуды", "Superfoods"],
           [5, "Мёд", "Honey"],
           [6, "Мука", "Flour"],
           [6, "Смеси для выпечки без глютена", "Baking mixtures without gluten"],
           [7, "Для жарки", "For frying"],
           [7, "Холодного отжима", "Cold spin"],
           [8, "Специи и соли", "Spices and salt"],
           [8, "Соусы", "Sauces"],
           [9, "Заменители сахара", "Sugar substitutes"],
           [10, "Сиропы, джемы и топпинги", "Syrups, jams and toppings"],
           [10, "Ореховые пасты", "Walnut pastes"],
           [11, "Печенье и крекеры", "Cookies and crackers"],
           [11, "Зефиры и мармелад", "Zephyrs and Marmelad"],
           [11, "Халва", "Halva"],
           [11, "Батончики на любой вкус и цвет", "Bars for every taste and color"],
           [11, "Шоколад, конфеты и леденцы", "Chocolate, sweets and candies"],
           [12, "Хлопья и мюсли", "Cereals and muesli"],
           [12, "Каши и манки", "Porridge and semolina"],
           [13, "Чипсы и снэки", "Чипсы и снэки"],
           [14, "Хлебцы", "Bread"],
           [15, "Орехи", "Nuts"],
           [15, "Пастила", "Paste"],
           [15, "Сухофрукты", "Dried fruits"],
           [16, "Макароны и лапша", "Pasta and noodles"],
           [16, "Крупы", "Groups"],
           [17, "Колбасы, мясо и тофу", "Sausages, meat and tofu"],
           [18, "Яйца куриные", "Chicken eggs"]
]